apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hapcontainers.cloudian.com
spec:
  group: cloudian.com
  names:
    kind: HapContainer
    listKind: HapContainerList
    plural: hapcontainers
    singular: hapcontainer
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: HapContainer is the Schema for the hapcontainers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: HapContainerSpec defines the desired state of HapContainer
          properties:
            image:
              minLength: 1
              type: string
          required:
          - image
          type: object
        status:
          description: HapContainerStatus defines the observed state of HapContainer
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
