apiVersion: v1
kind: Namespace
metadata:
  name: cloudian
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: hap-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - hap-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - hap.cloudian.com
  resources:
  - '*'
  - hscoperators
  - hfsoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hsc-operator.cloudian.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hfs-operator.cloudian.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hap-operator
subjects:
- kind: ServiceAccount
  name: hap-operator
roleRef:
  kind: Role
  name: hap-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hap-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: 'hyperstore-operator-rolebinding'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'hyperstore-operator-role'
subjects:
- kind: ServiceAccount
  name: default
  namespace: 'cloudian'
---
apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJZWFJsYTJGa1pUcFBaMGN6VGsxQ1MwbGlWVEp2UTFOcldqY3dXVUZGWkhsWGFGUnlkbE5rUTI1dFVHNVZaMmcyZWk5MVNWUXdlRmx3V1dFcmNFY3ZXSEJDUms4cmQwdGllSEpQV2tWWVNFaDFOV1o1UTJvekswdHhhemRpY1hacVNVOXlSVEJ4TVhNd1ptaDFaMEV4VjNOcVJUMD0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
kind: Secret
metadata:
  name: 'hyperstore-regcred'
  namespace: 'cloudian'
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hap-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hap-operator
  template:
    metadata:
      labels:
        name: hap-operator
    spec:
      serviceAccountName: hap-operator
      containers:
        - name: hap-operator
          # Replace this with the built image name
          image: quay.io/cloudian/hap-operator
          command:
          - hap-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "hap-operator"
