apiVersion: apps/v1
kind: Deployment
metadata:
  name: hap-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hap-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: hap-operator
    spec:
      serviceAccountName: hap-operator
      containers:
        - name: hap-operator
          # Replace this with the built image name
          image: nvijayaraju/hapcontainer-operator:dev
          command:
          - hap-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom: ""
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "hap-operator"
