kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hap-operator
subjects:
- kind: ServiceAccount
  name: hap-operator
  namespace: 
roleRef:
  kind: ClusterRole
  name: hap-operator
  apiGroup: rbac.authorization.k8s.io
