apiVersion: v1
kind: ConfigMap
metadata:
  name: busybox-config
  namespace: default
data:
  busybox.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: busybox1
      labels:
        app: busybox1
    spec:
      containers:
      - image: busybox
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
        name: busybox
      restartPolicy: Always