apiVersion: v1
kind: ConfigMap
metadata:
  name: hfs-config
  namespace: default
data:
  log_level: INFO
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  namespace: default
data:
  log_level: INFO